### ISSUE TITLE
Stand Up Manual Mainnet Sync Node to Collect Chain Data

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/engineering#22]
We need to begin collecting EOS mainnet chain data in order to build a full-chain parallel replay system (aka "chickens" test). It may take a very long time to collect this chain data - six months or more. The first step in a chickens test is to begin collecting this data. This will also be useful to provide ENF engineers fast and reliable P2P and HTTPS API endpoints.

This ticket is to _manually_ stand up a "sync node" to sync to EOS mainnet from public peers and collect chain data for these and other purposes.

Part of this ticket is also to create initial cost estimates for such nodes. A back-of-the-napkin estimate was $365/mo, but a more accurate and specific estimate is a deliverable for this ticket.

**Comment by kj4ezj** [comment]
@wanderingbort approved the cloud spend for one persistent EOS mainnet sync node on 2023-01-24.

**Comment by kj4ezj** [comment]
Consensus from senior engineers is that 64 GB RAM is an absolute minimum, and we should seek the highest reasonable single-threaded performance. I looked through [ec2instances.info](https://instances.vantage.sh/?min_memory=64&selected=r6a.2xlarge,r6i.2xlarge,r6id.2xlarge,i4i.2xlarge,m6a.4xlarge,r6in.2xlarge) and [found](https://browser.geekbench.com/v5/cpu/multicore?page=60) the Intel Xeon 8375C to have the highest single-threaded performance within a reasonable price range, followed by the AMD EPYC 7R13. These correspond to an `r6a.2xlarge` or `r6i.2xlarge` instance type in the current offerings for ~$331.13/mo or ~$367.92/mo not including storage. Engineers suggest >3 TB is needed for the current `blocks.log` and that storage speed would not be a significant factor if `database-map-mode=heap`, so for a 4096 GB GP3 SSD EBS partition at the minimum speed of 125 MB/s, that comes to $327.68/mo regardless of instance type.

So:
- `r6a.2xlarge` with 4096 GB GP3 SSD EBS-backed storage - ~$658.81/mo
- `r6i.2xlarge` with 4096 GB GP3 SSD EBS-backed storage - ~$695.60/mo

These costs can be reduced significantly by entering into a one year or three year agreement with AWS. For example, for an `r6a.2xlarge`, the cost comes down to ~$204.44/mo if paid for a year upfront for a total cost with EBS storage of $532.12/mo. It is cheaper in three year increments.

Engineers have also suggested buying our own hardware and co-locating it in a datacenter.

**Comment by matthewdarwin** [comment]
People will share their blocks.log if you ask nicely.   Would speed up syncing time and then you can replay locally.

**Comment by wanderingbort** [comment]
No longer necessary
