### ISSUE TITLE
Upgrade to C++20

### ISSUE THREAD

**Issue by wanderingbort** [eosnetworkfoundation/engineering#27]
[Transferred from legacy agenda on behalf of @greg7mdp and @ScottBailey]

(Should we) consider switching to -std=c++20 for leap and appbase? (@greg7mdp)

It’s 2023, can we have FULL C++20 support? If now isn’t the right time, when is? (@ScottBailey)

**Comment by wanderingbort** [comment]
[Transferred from legacy agenda on behalf of @ericpassmore ]

Hmm I'm running  /lib32/libstdc++.so.6 today. What version should I be targeting for leap build from main?

**Comment by wanderingbort** [comment]
[Transferred from legacy agenda on behalf of @spoonincode ]

neither gcc nor clang have released FULL c++20 support

**Comment by ScottBailey** [comment]
Maybe it is more appropriate to talk about the C++20 features we'd like to use, Matt is correct, full support for C++20 doesn't exist yet. 

I think this [list](https://en.cppreference.com/w/cpp/compiler_support#cpp20) might be fairly up to date.

I'd like to use std::span and 3 way comparison operator (<=>).

**Comment by spoonincode** [comment]
With ubuntu 18 being dropped, I def think we should go ahead and move up to 20 (well, maybe until after the release is cut). But with no compiler fully supporting 20, we need to decide on the minimum compiler we'll target. gcc10 seems reasonable as at least there is a ubuntu20 package and it has most of the good stuff.

**Comment by greg7mdp** [comment]
Yes, it would be great to move to C++20, and indeed most of the good c++20 stuff is in gcc 10.

Newer compilers can be install if we add the following repository:

`sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test`

I have been building with `g++-12` for a while.

Also, it is very easy to install any clang version with:
```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh <version number> all
```

**Comment by ScottBailey** [comment]
> Yes, it would be great to move to C++20, and indeed most of the good c++20 stuff is in gcc 10.
> 
> Newer compilers can be installed if we add the following repository:

I am a little uncomfortable asking users to install packages outside their basic distro. BUT I'm also interested in using newer tools. Ubuntu 20 is near 3 years old, so I suppose it's a reasonable trade off to ask a user to upgrade either their compiler or OS.

It would be nice to target g++-12 as our "supported" complier.

**Comment by wanderingbort** [comment]
2.28 meeting notes:

Open Questions:
- does enabling c++20 in compilers have any effect on consensus (even with using the c++20 features)?
- how do we handle patches and backports? (policy needed?)
- what c++20 features are actually supported in our compilers?
 
Decisions to vote on:
- After 4.0? ✔️ 
- dependent on "chicken test" ? ❔

**Comment by greg7mdp** [comment]
So we are now `After 4.0`.
Decision was made to add the -std=c++20 switch.
I believe gcc-9 and gcc-10 are available by default. So I think it would be reasonable to specify gcc-10 as the minimum version supported.

1. install gcc-10 on ubuntu 20.04.1
```
apt update -y
apt upgrade -y
apt install -y build-essential
apt install -y gcc-10 g++-10 cpp-10
```

2. make it the default compiler (optional)
```

**Comment by spoonincode** [comment]
The way I read the 2.28 notes above was that the vote was only to defer this decision until post 4.0 branch. There appears to be outstanding questions still? For example
> dependent on "chicken test" ? ❔

**Comment by wanderingbort** [comment]
Upon further reflection the group is unconvinced that compiler flags would be a material risk for the semantics and therefore chicken testing shouldn't be considered a pre-requisite. 

Open Question 
- for product: are BPs largely using pinned builds? May be more of a concern for compilers/boost changes rather than c++ std.
- Confidence over consensus semantics, is the "chicken test" enough? 
- Does any undefined behavior become defined in c++20?

**Comment by greg7mdp** [comment]
> We talked about this briefly on the engineering weekly meeting video call, but the "chickens test" is a colloquialism 

Thanks Zach, this seems like an excellent test indeed!
