### ISSUE TITLE
AWS Account for the GameFi Frontend Team

### ISSUE THREAD

**Issue by AlexGriffith10** [eosnetworkfoundation/engineering#43]
Would like to get AWS access for the Frontend Engineering team that is investigating GameFi. We will be doing exploratory work into new projects using the EOS-EVM and would like to deploy these projects to test environments. 

Team members
- @ericpassmore 
- @AlexGriffith10 
- @RayMPerry 
- @kellytran3k 
- @juanm95 

What we need
- Ability to setup and deploy new services in AWS
- Host postgres DBs
- S3
- SQS (not sure if we'll still need queuing capability with the pivot but nice to have just in case)

**Comment by kj4ezj** [comment]
Based on IM discussion with @AlexGriffith10, I will start by providing access to the following resources in `us-east-1`.
- EC2
- RDS
- S3
- SQS
- SSM

We can always add or remove AWS services or regions at any time.

**Comment by kj4ezj** [comment]
I created an AWS account called `frontend-sandbox`, required two-factor authentication for all users, restricted all resources to one region, granted access to the services listed above, then created all the IAM users. I logged in with a test user and things looked good.

I shared first login credentials and instructions with my customers in an encrypted message that will self-destruct shortly. The decryption key was sent out-of-band. AWS will require a password reset on first login and two-factor authentication will have to be enabled to see or do anything.

Please reach out if you need any help! We can expand the services, add regions, add users, or whatever else.
