### ISSUE TITLE
Point DNS to ide.eosnetwork.com

### ISSUE THREAD

**Issue by nsjames** [eosnetworkfoundation/engineering#54]
We want to launch the web IDE on `ide.eosnetwork.com`. In order to do so, we need to point the DNS to the hosted zone. 

I've forwarded the information to @kj4ezj in a private message, this ticket is merely for tracking purposes.

**Comment by kj4ezj** [comment]
Done!

![2023-08-28 17-35-18 - DNS - ide eosnetwork com](https://github.com/eosnetworkfoundation/engineering/assets/34947245/7c675496-f5d6-44c6-a742-2aefb3079c77)
