### ISSUE TITLE
Fix EVM CloudWatch Alerts

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/engineering#66]
Customers have not been getting email alerts surrounding EVM cloud infrastructure health check status changes. The email alerts are working with test events, so there must be something wrong with CloudWatch or between CloudWatch and the SNS topic. Debug and fix this so alerts start flowing again.

## See Also
1. eos-evm [issue 602](https://github.com/eosnetworkfoundation/eos-evm/issues/602) - Funnel EVM Health Checks into CloudWatch
1. engineering [issue 48](https://github.com/eosnetworkfoundation/engineering/issues/48) - Collaborate with Operations on Unified Dashboarding Solution
1. engineering [issue 49](https://github.com/eosnetworkfoundation/engineering/issues/49) - Create Bot to Alert via IM on Specific Metrics
1. eos-evm [issue 603](https://github.com/eosnetworkfoundation/eos-evm/issues/603) - **SMS** Alerting for EVM Infrastructure Health Checks
1. engineering [issue 65](https://github.com/eosnetworkfoundation/engineering/issues/65) - **Email** Alerting for EVM Infrastructure Health Checks
1. telegram-bot [issue 1](https://github.com/eosnetworkfoundation/telegram-bot/issues/1) - Open-Source This Repo
1. engineering [issue 57](https://github.com/eosnetworkfoundation/engineering/issues/57) - Create Telegram Service Account
1. engineering [issue 58](https://github.com/eosnetworkfoundation/engineering/issues/58) - Create EVM **Testnet** Alert Channel Using Telegram Service Account
1. engineering [issue 64](https://github.com/eosnetworkfoundation/engineering/issues/64) - Create EVM **Mainnet** Alert Channel Using Telegram Service Account
1. engineering [issue 66](https://github.com/eosnetworkfoundation/engineering/issues/66) - Fix EVM CloudWatch Alerts

**Comment by wanderingbort** [comment]
This is considered done

**Comment by kj4ezj** [comment]
Alerts are flowing in US region(s), but there are technical limitations preventing alerts for APAC infrastructure from flowing. These technical limitations will be addressed in a subsequent ticket, linked above and in the parent epic. This does not impair EVM readiness because of the way the system is architected. APAC infrastructure outages will failover to US infrastructure, which saw alerts fixed as part of this ticket.
