### ISSUE TITLE
EVM Alerts for APAC Infrastructure

### ISSUE THREAD

**Issue by wanderingbort** [eosnetworkfoundation/engineering#71]
Due to limitations in Amazon Web Services (AWS) offerings, it is not trivial to collect events from multiple AWS regions. Infrastructure alerts are flowing from the US region(s), but not APAC region(s).

There are better long-term solutions but, for now, it will be fastest and easiest to stand up parallel infrastructure in APAC alerting directly to IM. This ticket is to do that.

## See Also
**engineering [issue 68](https://github.com/eosnetworkfoundation/engineering/issues/68) - EVM Monitoring and Alerting - Phase 1**
1. eos-evm [issue 602](https://github.com/eosnetworkfoundation/eos-evm/issues/602) - Funnel EVM Health Checks into CloudWatch
1. engineering [issue 48](https://github.com/eosnetworkfoundation/engineering/issues/48) - Collaborate with Operations on Unified Dashboarding Solution
1. engineering [issue 49](https://github.com/eosnetworkfoundation/engineering/issues/49) - Create Bot to Alert via IM on Specific Metrics
1. eos-evm [issue 603](https://github.com/eosnetworkfoundation/eos-evm/issues/603) - **SMS** Alerting for EVM Infrastructure Health Checks
1. engineering [issue 65](https://github.com/eosnetworkfoundation/engineering/issues/65) - **Email** Alerting for EVM Infrastructure Health Checks
1. telegram-bot [issue 1](https://github.com/eosnetworkfoundation/telegram-bot/issues/1) - Open-Source This Repo
1. engineering [issue 57](https://github.com/eosnetworkfoundation/engineering/issues/57) - Create Telegram Service Account
1. engineering [issue 58](https://github.com/eosnetworkfoundation/engineering/issues/58) - Create EVM **Testnet** Alert Channel Using Telegram Service Account
1. engineering [issue 64](https://github.com/eosnetworkfoundation/engineering/issues/64) - Create EVM **Mainnet** Alert Channel Using Telegram Service Account
1. engineering [issue 66](https://github.com/eosnetworkfoundation/engineering/issues/66) - Fix EVM CloudWatch Alerts
1. telegram-bot [issue 2](https://github.com/eosnetworkfoundation/telegram-bot/issues/2) - Human-Friendly Alerts
1. engineering [issue 71](https://github.com/eosnetworkfoundation/engineering/issues/71) - EVM Alerts for APAC Infrastructure
1. telegram-bot [issue 3](https://github.com/eosnetworkfoundation/telegram-bot/issues/3) - Alert Bot Maintainer via Telegram on Errors

**Comment by kj4ezj** [comment]
I found that [AWS EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html) supports cross-account and cross-region event handling as of Sprint 2021. I am already using EventBridge to deliver CloudWatch alarm events to my notification system in the US, so I am working on pointing EventBridge in APAC to the existing US infrastructure. This will prevent the need for duplicate code/infrastructure across regions.

### Relevant AWS Documentation
Here are some helpful resources showing this is possible and explaining how to do it.
- [Introducing cross-Region event routing with Amazon EventBridge](https://aws.amazon.com/blogs/compute/introducing-cross-region-event-routing-with-amazon-eventbridge/)
- [Sending and receiving Amazon EventBridge events between AWS Regions](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cross-region.html)
- [A step-by-step guide to cross-account and cross-region events with EventBridge](https://repost.aws/articles/ARIw6q_ozaTmqqI25Eq4YIcQ/a-step-by-step-guide-to-cross-account-and-cross-region-events-with-eventbridge)

**Comment by kj4ezj** [comment]
Done!

This was easy to implement and should be extremely reliable. I received an event from APAC on Telegram and via email for both the `evm-mainnet` and `evm-testnet` AWS account.
