### ISSUE TITLE
EVM Monitoring and Alerting - Phase 2

### ISSUE THREAD

**Issue by wanderingbort** [eosnetworkfoundation/engineering#73]
Place holder for future items 

Needs to wait for phase 1 to be used and feedback prepared 
```[tasklist]
### Tasks
```

**Comment by kj4ezj** [comment]
While responding to [an alert](https://t.me/c/1955944692/25) setup during phase one of this project, the customers shared a graph of CPU utilization and explained the instance needs to be restarted.

![Image](https://github.com/eosnetworkfoundation/engineering/assets/34947245/b0297680-d6a1-429e-8b8f-0cbeb8a45835)

This suggests to me that CPU utilization and instance uptime or restarts might be good metrics to plan for dashboarding and/or alerting in phase 2.

**Comment by kj4ezj** [comment]
We will need to provide the customer some way to declare a maintenance period during which alarms should be suppressed.

![2023-10-24 15-36-33 - EVM alarms during maintenance period](https://github.com/eosnetworkfoundation/engineering/assets/34947245/4b9bf33b-f5ae-42c0-9c52-f6c5f6245e7d)

**Comment by wanderingbort** [comment]
Blocked by infrastructure transition to EOS Labs

**Comment by wanderingbort** [comment]
Closing as waiting for something to do
