### ISSUE TITLE
Reserve Instance Survey

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/engineering#83]
@tedcahalleos asked me to provide a list of cloud instances and what they are allocated for in order to plan reserve instances to minimize cloud spend.

> Would you be able to tell me the number and type of instances we have in [the US and APAC]?
> - by type
> - by ENV (prod vs test)

**Edit:**  
Turns out, this request originated from EOS Labs. This ticket also includes their request for an EVM AWS cost analysis.

**Comment by wanderingbort** [comment]
This is still a priority, sorry for distracting you from it.

**Comment by Joshua2Mars** [comment]
Thanks for provide the cost analysis!
