### ISSUE TITLE
Review Chicken-Dance OAuth PR

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/engineering#97]
Review PR https://github.com/eosnetworkfoundation/chicken-dance/pull/96

**Comment by ericpassmore** [comment]
Can I get an approval on the PR? In addition to resolving comments, made changes since last review 
1) added HTTP API authentication via `Authenticate` header
2) allow multiple teams for access control
3) more secure check authentication and access on every API request.

**Comment by kj4ezj** [comment]
Approved and merged.
